version: "3.11"

services:
  db:
    image: postgres:15
    container_name: anime-academy-postgres
    networks:
      - my_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"


  backend:
    build:
      context: backend
    container_name: anime-academy-backend
    ports:
      - "8000:8000"
    volumes:
      - media:/media
    command: sh /backend/entrypoint.sh
    networks:
      - my_network
    depends_on:
      - db


  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
    restart: always


volumes:
  media:

networks:
  my_network:
