"""add anime series table

Revision ID: 39625bc385d7
Revises: 254bdcda32f4
Create Date: 2025-05-20 21:08:38.321716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39625bc385d7'
down_revision: Union[str, None] = '254bdcda32f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('iframe_html', sa.Text(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('anime', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('episodes', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('status', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('season', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('studio', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('mpaa_rating', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('age_restrictions', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('poster_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'poster_url')
    op.drop_column('anime', 'age_restrictions')
    op.drop_column('anime', 'mpaa_rating')
    op.drop_column('anime', 'studio')
    op.drop_column('anime', 'season')
    op.drop_column('anime', 'source')
    op.drop_column('anime', 'status')
    op.drop_column('anime', 'episodes')
    op.drop_column('anime', 'type')
    op.drop_table('anime_series')
    # ### end Alembic commands ###
