"""add has_reply

Revision ID: c4ae695f0ae8
Revises: 6c481ca23cf4
Create Date: 2025-05-29 20:16:50.455812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ae695f0ae8'
down_revision: Union[str, None] = '6c481ca23cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_comments', sa.Column('has_reply', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_comments', 'has_reply')
    # ### end Alembic commands ###
