"""add status for anime

Revision ID: e703f159a1a3
Revises: f0e6a64cee7f
Create Date: 2025-04-25 21:43:43.482815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e703f159a1a3'
down_revision: Union[str, None] = 'f0e6a64cee7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorites', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_favorites', 'status')
    # ### end Alembic commands ###
