"""add m2m connection

Revision ID: f6bc915b068a
Revises: 3694a1e4ddcc
Create Date: 2025-05-12 18:50:29.995526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bc915b068a'
down_revision: Union[str, None] = '3694a1e4ddcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anime_genres_genre_id_fkey', 'anime_genres', type_='foreignkey')
    op.drop_constraint('anime_genres_anime_id_fkey', 'anime_genres', type_='foreignkey')
    op.create_foreign_key(None, 'anime_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anime_genres', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    op.drop_column('anime_genres', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_genres', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'anime_genres', type_='foreignkey')
    op.drop_constraint(None, 'anime_genres', type_='foreignkey')
    op.create_foreign_key('anime_genres_anime_id_fkey', 'anime_genres', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key('anime_genres_genre_id_fkey', 'anime_genres', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
